package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v18 -> v19 migration: `skippedSetsJson` on sessions, the prescribed sets
 * the lifter deliberately did not do (#300), and `durationEndedBy` on
 * `set_records`, which of the four things that can end a hold produced its
 * recorded seconds (#259).
 *
 * ## A NEW HOP, not an extension of 18 -- and TWO COLUMNS on it
 *
 * v0.1.53 SHIPS `DATABASE_VERSION = 18`, read by
 * `git show v0.1.53:core/data/src/main/kotlin/com/macrophage/barspeed/data/AppDatabase.kt`
 * rather than assumed, so an installed build has run 17 -> 18 and extending that
 * hop would leave a device that already migrated without the new column.
 * [Migration16To17Test] states the opposite case and the same test: two columns
 * rode one hop there BECAUSE 17 had not shipped.
 *
 * The SAME test is why #259's column rides this hop instead of opening 19 -> 20:
 * 19 itself has not shipped either, so nothing has migrated to it and no phone
 * can be left behind. Re-read at the tag this round, not inherited from the
 * paragraph above.
 *
 * ## Why a column at all
 *
 * Nothing in the export publishes how many sets a plan prescribed -- `planRef`
 * is a name and `$defs.exercise` carries exactly `exercise` and `sets` -- and
 * the plan is not in the export and may be edited or deleted after the session
 * it drove, so the prescribed count cannot be recovered later. Until #300 no
 * control could drop ONE prescribed set: a hole was always the whole remainder
 * of a session. With one droppable mid-session, an exercise carrying three sets
 * where four were prescribed is indistinguishable from a plan that asked for
 * three and from a set the app lost, and the app's own dominant failure mode is
 * the third. This column is what separates a decision from a loss.
 *
 * ## Why on the session
 *
 * There is no set to hang it on. The skipped slot never ran, so no `set_records`
 * row, no raw stream and no export entry exists for it, and writing a row to
 * carry the skip would put a set that did not happen into the lifter's history
 * -- which is what `VoidedSet` exists to undo. Every count over `set_records`
 * would then have to learn to exclude it.
 *
 * ## The shape
 *
 * TEXT, NULLABLE, NO DEFAULT. A JSON array of `:core:model`'s `SkippedSet`, the
 * same type the export publishes, so the column and `session.json` cannot drift
 * apart over the names. Nullable because no build before v19 could record a
 * skip. NO DEFAULT because an empty array on every existing row would say each
 * of those sessions was checked and had none -- absence rendered as a value, and
 * the one reading that turns "the app could not tell" into "the plan was
 * completed".
 *
 * ## What this verifies, exactly
 *
 * [Migration17To18Test]'s instrument, one hop later, and that file states the
 * method: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the DIFFERENCE
 * between `schemas/.../18.json` and `schemas/.../19.json`, both generated by the
 * Room compiler from the entities rather than written by hand. Nothing here
 * executes SQL -- there is no SQLite on this module's test classpath and no
 * `androidTest` source set anywhere -- so this cannot say that SQLite accepts
 * the statement, that a real file survives it, or that Room's own `TableInfo`
 * check passes afterwards. A bench run against the emulator is OWED for those,
 * and #300's own [Field] section says so.
 *
 * NOT A DIFFERENTIAL. Every test here passes at the commit that adds it, which
 * also adds the hop: the migration and its pins arrive together because a
 * declared-and-unregistered hop fails on the lifter's phone rather than anywhere
 * a test can see it. The red on this branch is elsewhere -- nothing yet carries
 * a skip INTO this column or out of it to the document.
 */
class Migration18To19Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_18_19.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration17To18Test] the way that file took it from its predecessor: a
     * constant left behind at 18 ships a build whose schema the chain cannot
     * reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on nineteen`() {
        assertEquals(19, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(19, declaredVersion(19), "19.json does not describe version 19")
        assertEquals(18, declaredVersion(18), "18.json does not describe version 18")
        assertEquals(18, AppDatabase.MIGRATION_18_19.startVersion)
        assertEquals(19, AppDatabase.MIGRATION_18_19.endVersion)
    }

    /**
     * v19 differs from v18 by exactly two nullable TEXT columns: the skip list
     * on sessions and the hold-end provenance on set_records.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a third column, a retyped column and a dropped
     * one are all caught -- none of which the statements below would carry.
     */
    @Test
    fun `the schema baselines differ by exactly the skip list and the hold-end word`() {
        for (table in listOf("raw_streams", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(19, table) - columnsOf(18, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(19, "sessions") - columnsOf(18, "sessions").keys
        assertEquals(setOf("skippedSetsJson"), gained.keys, "sessions gained something other than the skip list")
        val (affinity, notNull, default) = gained.getValue("skippedSetsJson")
        assertEquals("TEXT", affinity, "skippedSetsJson is not TEXT, so it cannot hold the encoded list")
        assertTrue(!notNull, "skippedSetsJson is NOT NULL, so a session that skipped nothing cannot be stored")
        assertNull(default, "skippedSetsJson carries a default, which is an answer nobody gave")

        // #259's column, riding the same unreleased hop. TEXT because the value
        // is `HoldEndSource`'s published word; nullable and defaultless because
        // no build before v19 could say what ended a hold, and a default word
        // would answer for every hold already in the archive.
        val gainedOnSets = columnsOf(19, "set_records") - columnsOf(18, "set_records").keys
        assertEquals(
            setOf("durationEndedBy"),
            gainedOnSets.keys,
            "set_records gained something other than the hold-end word",
        )
        val (setAffinity, setNotNull, setDefault) = gainedOnSets.getValue("durationEndedBy")
        assertEquals("TEXT", setAffinity, "durationEndedBy is not TEXT, so it cannot hold the published word")
        assertTrue(!setNotNull, "durationEndedBy is NOT NULL, so a set that is not timed cannot be stored")
        assertNull(setDefault, "durationEndedBy carries a default, which answers for every hold ever recorded")
    }

    /**
     * Nothing that existed at v18 changed -- and the session's own frozen
     * columns above all.
     *
     * The near neighbour of adding a column to `sessions` is retyping the ones
     * written beside it at the same moment. `sessionRpe` and `hrvRmssdMs` are
     * written by the same call this list will be written by, so a silently
     * retyped one of those would change what a stored session says rather than
     * failing loudly.
     */
    @Test
    fun `no column that existed at v18 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(18, table)
            val after = columnsOf(19, table)
            assertEquals(emptyList(), before.keys.filter { it !in after }, "$table lost a column between v18 and v19")
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v18",
            )
        }
        val v19 = columnsOf(19, "sessions")
        assertEquals(Triple("INTEGER", false, null), v19.getValue("sessionRpe"), "sessionRpe changed shape")
        assertEquals(Triple("REAL", false, null), v19.getValue("hrvRmssdMs"), "hrvRmssdMs changed shape")
    }

    /**
     * The migration executes exactly the two appends the baselines call for,
     * and nothing else.
     *
     * TWO, not one, because 19 has not shipped: v0.1.53 carries
     * `DATABASE_VERSION = 18`, read at the tag this round, so no phone has run
     * 18 -> 19 and #259's column can ride the hop rather than needing 19 -> 20.
     * The count is asserted as a whole list so a third statement cannot arrive
     * unnoticed.
     */
    @Test
    fun `the migration runs the two add-column statements and nothing else`() {
        assertEquals(
            listOf(
                "ALTER TABLE sessions ADD COLUMN skippedSetsJson TEXT",
                "ALTER TABLE set_records ADD COLUMN durationEndedBy TEXT",
            ),
            executedSql(),
        )
    }

    /**
     * A plain append that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table definition,
     * while every form Room would generate for a table recreate copies rows --
     * which on this schema means copying every gzipped IMU blob in the lifter's
     * history.
     */
    @Test
    fun `the statement is a plain append and is not destructive`() {
        assertTrue(executedSql().isNotEmpty(), "the migration executes nothing at all")
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is given a skip list.
     *
     * There is nothing to backfill FROM, and that is the point rather than a
     * limitation. A session that ended early dropped its remaining sets
     * silently: nothing was written in the journal, in the row or in the export,
     * so no artifact anywhere says whether the lifter chose to stop or ran out
     * of time. Writing an empty array would claim the question was asked and
     * answered for every session in the archive.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a decision nobody made",
        )
    }

    /**
     * The hop is REGISTERED, which the statements above cannot say.
     *
     * A migration declared and not passed to `addMigrations` is a migration Room
     * never runs, and the failure lands on the lifter's phone as an
     * `IllegalStateException` on open. Read off the declared list rather than off
     * `build`, which needs a `Context`.
     */
    @Test
    fun `the hop is in the chain the database is built with`() {
        assertEquals(
            (1..18).map { it to it + 1 },
            AppDatabase.MIGRATIONS.map { it.startVersion to it.endVersion },
            "the migration chain is not an unbroken 1 -> 19",
        )
    }
}
