package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v10 -> v11 migration, read against Room's own committed descriptions of
 * the two schemas.
 *
 * ## What this does and does not verify, exactly
 *
 * It DOES run the real [AppDatabase.Companion.MIGRATION_10_11] body -- not a
 * copy of its SQL -- by handing it a `SupportSQLiteDatabase` that records what
 * it is asked to execute, and it compares the result against the DIFFERENCE
 * between `schemas/…/10.json` and `schemas/…/11.json`, both of which are
 * generated by the Room compiler from the entities rather than written by
 * hand. So a column added to an entity and forgotten in the migration is
 * caught here, and so is the reverse.
 *
 * It does NOT execute any SQL. Nothing in this repository can: `:core:data`'s
 * tests run on the JVM against android.jar stubs, there is no SQLite on the
 * test classpath and no `androidTest` source set anywhere. So this cannot say
 * that SQLite accepts these statements, that the file on a phone survives
 * them, or that Room's own `TableInfo` check passes afterwards. Those are the
 * emulator exercise, which for the v0.1.44 cluster runs once at the end, after
 * #161, before the cut -- #159 is this commit's own issue and has extended the
 * migration rather than discharged that exercise. Until it has run, this
 * migration is UNEXECUTED and this file is the strongest thing that can be said
 * about it from a JVM.
 *
 * The recording database is a `java.lang.reflect.Proxy` rather than a
 * hand-written fake, deliberately. `SupportSQLiteDatabase` has some three
 * dozen members; a Kotlin fake would be that many stubs, every one of which
 * would have to be revisited on a library bump, and the one method under
 * observation would be lost among them. A proxy records `execSQL` and answers
 * null to everything else, which is exactly the surface a migration made of
 * `ALTER TABLE` statements touches -- and if a future edit to the migration
 * reaches for anything that needs a real return value, this test fails loudly
 * rather than quietly passing.
 */
class Migration10To11Test {
    private val json = Json { ignoreUnknownKeys = true }

    /**
     * Room writes the exported schemas to `$projectDir/schemas`
     * (`core/data/build.gradle.kts`), and a Gradle `Test` task runs with its
     * project directory as the working directory. Both fallbacks are here
     * because a green run against a file that was not found is the
     * green-where-nothing-ran class: this throws with the paths it tried
     * rather than skipping.
     */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_10_11.migrate(recorder)
        return executed
    }

    // ---- the baselines themselves -------------------------------------------

    /**
     * The committed baseline and the migration's own endpoints are one number,
     * and the compiled version is at or beyond it.
     *
     * THE MIDDLE ASSERTION USED TO READ `assertEquals(11, DATABASE_VERSION)`
     * and it was corrected rather than deleted, because what it was reaching
     * for is still worth pinning. It was true while 11 was the newest hop and
     * went false the moment #177 added a twelfth: an intermediate hop's end
     * version is not the compiled version and never was, and asserting they are
     * equal makes every future bump red this file for no defect. What the hop
     * genuinely owes the constant is that the chain still reaches it -- a hop
     * ending BEYOND `DATABASE_VERSION` is a build whose migration list
     * overshoots its own schema.
     *
     * The exact-11 assertions below are untouched. An entity changed with this
     * migration left behind still ships a build whose schema the chain cannot
     * produce, and Room throws on the lifter's phone; that is what
     * [Migration11To12Test] asserts for the newest hop, including the
     * `DATABASE_VERSION` equality this test can no longer carry.
     */
    @Test
    fun `the committed baseline and the migration agree on eleven, within a chain that reaches the compiled version`() {
        assertTrue(
            AppDatabase.MIGRATION_10_11.endVersion <= DATABASE_VERSION,
            "this migration ends beyond DATABASE_VERSION, so the chain overshoots the schema this build compiles",
        )
        assertEquals(11, declaredVersion(11), "11.json does not describe version 11")
        assertEquals(10, declaredVersion(10), "10.json does not describe version 10")
        assertEquals(10, AppDatabase.MIGRATION_10_11.startVersion)
        assertEquals(11, AppDatabase.MIGRATION_10_11.endVersion)
    }

    /**
     * v11 differs from v10 by exactly three columns: two nullable TEXT and one
     * nullable INTEGER, none of them defaulted.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so it sees a fourth column, a retyped column and
     * a dropped one alike -- none of which the SQL below would carry.
     *
     * The affinity is asserted PER COLUMN rather than over the union, since
     * #159 put a column of a different type in the same migration. Asserting
     * one shared affinity over all three would have had to be weakened to pass,
     * and a weakened assertion is how `sessionRpe INTEGER` and a `sessionRpe
     * TEXT` in the entity stop being distinguishable.
     */
    @Test
    fun `the schema baselines differ by exactly the three columns the migration appends`() {
        val rawAdded = columnsOf(11, "raw_streams") - columnsOf(10, "raw_streams").keys
        val setAdded = columnsOf(11, "set_records") - columnsOf(10, "set_records").keys
        val sessionAdded = columnsOf(11, "sessions") - columnsOf(10, "sessions").keys

        assertEquals(setOf("role"), rawAdded.keys, "raw_streams gained something other than role")
        assertEquals(setOf("sensorsJson"), setAdded.keys, "set_records gained something other than sensorsJson")
        assertEquals(setOf("sessionRpe"), sessionAdded.keys, "sessions gained something other than sessionRpe")

        val expectedAffinity = mapOf("role" to "TEXT", "sensorsJson" to "TEXT", "sessionRpe" to "INTEGER")
        for ((name, spec) in rawAdded + setAdded + sessionAdded) {
            val (affinity, notNull, default) = spec
            assertEquals(
                expectedAffinity.getValue(name),
                affinity,
                "$name is not ${expectedAffinity.getValue(name)}, so the migration's column type is wrong",
            )
            assertTrue(!notNull, "$name is NOT NULL, which an ADD COLUMN with no default cannot produce")
            assertNull(default, "$name carries a default the migration does not write")
        }
    }

    /**
     * Nothing that existed at v10 changed.
     *
     * The near neighbour of adding a column is retyping one beside it, and a
     * migration made of ADD COLUMN statements says nothing about the rest of
     * the table -- so a silently retyped column would reach Room's own
     * TableInfo check on a real phone and throw there instead of here.
     */
    @Test
    fun `no column that existed at v10 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(10, table)
            val after = columnsOf(11, table)
            assertEquals(
                emptyList(),
                before.keys.filter { it !in after },
                "$table lost a column between v10 and v11",
            )
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v10",
            )
        }
    }

    // ---- the SQL the migration runs ------------------------------------------

    /**
     * The migration executes exactly the three statements the baselines call
     * for, in order, and nothing else.
     *
     * Read off the real migration body through a recording database, so this
     * is the SQL that will run rather than a second copy of it kept beside the
     * first.
     *
     * A LIST, so the order is pinned as well as the membership. Three plain
     * column appends against three different tables commute, so nothing breaks
     * if they are reordered -- but a reordering is still a change to what runs
     * on the lifter's phone, and the cheapest place to notice one is here.
     */
    @Test
    fun `the migration runs one plain add-column statement per new column`() {
        assertEquals(
            listOf(
                "ALTER TABLE raw_streams ADD COLUMN role TEXT",
                "ALTER TABLE set_records ADD COLUMN sensorsJson TEXT",
                "ALTER TABLE sessions ADD COLUMN sessionRpe INTEGER",
            ),
            executedSql(),
        )
    }

    /**
     * No statement carries NOT NULL or a DEFAULT, and that is what keeps them
     * cheap and non-destructive.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition; a NOT NULL column without a default is refused outright on a
     * non-empty table, and every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU
     * blob in the lifter's history. The cheapest correct statement is also the
     * only one that cannot lose a row.
     */
    @Test
    fun `no statement can rewrite a table or refuse a populated one`() {
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue("NOT NULL" !in sql, "a NOT NULL append is refused on a populated table: $sql")
            assertTrue("DEFAULT" !in sql.uppercase(), "a default here would disagree with the baseline: $sql")
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * Nothing already recorded is given a role, a sensor declaration or a
     * session rating.
     *
     * A backfill was refused twice over for the sensor columns: a role is
     * meaningless on an `hrm`, `rest_before_hrm`, `cues` or `reps` row, and on
     * an `imu` row it would state which physical unit a capture came from when
     * nobody assigned one. For `sessionRpe` it is sharper still -- how a past
     * workout FELT is recorded in no artifact this app has ever written, so any
     * value written here would be invented outright, and a midpoint would be
     * the most believable invention of all.
     *
     * This is the pin against a later "helpful" UPDATE being added to the
     * migration -- the shape the v8 -> v9 migration's own KDoc refused for
     * time zones, where a plausible value is indistinguishable from a measured
     * one.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a value nobody declared",
        )
    }
}
