package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v12 -> v13 migration, read against Room's own committed descriptions of
 * the two schemas.
 *
 * ## What this does and does not verify, exactly
 *
 * [Migration10To11Test]'s instrument, two hops later, and that file's KDoc
 * states the method once: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the
 * DIFFERENCE between `schemas/…/12.json` and `schemas/…/13.json`, both
 * generated by the Room compiler from the entities rather than written by
 * hand. Nothing here executes SQL -- there is no SQLite on this module's test
 * classpath and no `androidTest` source set anywhere -- so this cannot say
 * that SQLite accepts the statements, that a real file survives them, or that
 * Room's own `TableInfo` check passes afterwards. The emulator exercise is
 * what says that. It was run on AVD barspeed-api35 against a populated v12
 * file written by v0.1.44 and is recorded in 522356c's commit body; nothing in
 * CI executes SQL against this migration, so that run is the only thing that
 * ever has.
 *
 * ## Why this hop is shaped like v10 -> v11 and not like v11 -> v12
 *
 * All three columns are NULLABLE WITH NO DEFAULT, which is
 * [AppDatabase.MIGRATION_10_11]'s shape. The hop before this one appended a
 * NOT NULL column WITH a default, because `added` is a non-null `Boolean` and
 * SQLite refuses a NOT NULL append with no default on a populated table. Each
 * file asserts its own shape exactly rather than admitting both: a nullable
 * append and a defaulted non-null one fail in different directions, and an
 * assertion that accepts either cannot catch a column declared the wrong way
 * round.
 *
 * The nullability is not an implementation convenience. Each of the three has
 * a real absent state -- a reason never asked for, a note never typed, a
 * purpose the lifter never stated -- and a default on any of them would store
 * an answer nobody gave.
 *
 * ## THE HOP THE PHONE ACTUALLY RUNS IS THIS ONE, ALONE
 *
 * v0.1.44 was cut, at tag `7cf6e8c3cc546ab8d64c9fb2be86de2129250b43`, and it
 * carries `DATABASE_VERSION = 12`. So the 10 -> 11 -> 12 pair has shipped and
 * an install upgrading to this build runs 12 -> 13 by itself. That is the
 * opposite of the situation [Migration11To12Test]'s KDoc described while
 * v0.1.44 was still uncut, and both files are corrected here rather than left
 * to be read as current.
 */
class Migration12To13Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test.schema]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_12_13.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * THE FIRST ASSERTION USED TO READ `assertEquals(13, DATABASE_VERSION)`,
     * and it is corrected here exactly as [Migration11To12Test]'s was one hop
     * earlier and [Migration10To11Test]'s one before that, by the rule this
     * KDoc already stated: the equality belongs to the NEWEST hop and moves
     * every time one is added. It was true while 13 was the newest and went
     * false the moment #215 added a fourteenth. An intermediate hop's end
     * version is not the compiled version, and asserting they are equal reds
     * this file on every future bump for no defect. The equality is not
     * dropped -- it is in [Migration13To14Test], where it landed red at that
     * file's own commit while the constant still read 13.
     *
     * The exact-13 assertions below are untouched. An entity changed with this
     * migration left behind still ships a build whose schema the chain cannot
     * produce, and Room throws on the lifter's phone.
     */
    @Test
    fun `the baseline and the migration agree on thirteen, inside a chain reaching the compiled version`() {
        assertTrue(
            AppDatabase.MIGRATION_12_13.endVersion <= DATABASE_VERSION,
            "this migration ends beyond DATABASE_VERSION, so the chain overshoots the schema this build compiles",
        )
        assertEquals(13, declaredVersion(13), "13.json does not describe version 13")
        assertEquals(12, declaredVersion(12), "12.json does not describe version 12")
        assertEquals(12, AppDatabase.MIGRATION_12_13.startVersion)
        assertEquals(13, AppDatabase.MIGRATION_12_13.endVersion)
    }

    /**
     * v13 differs from v12 by exactly three columns on set_records, every one
     * of them nullable with no default.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a fourth column, a retyped column and a
     * dropped one are all caught -- none of which the three statements below
     * would carry.
     */
    @Test
    fun `the schema baselines differ by exactly the three nullable set columns`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(13, table) - columnsOf(12, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(13, "set_records") - columnsOf(12, "set_records").keys
        assertEquals(
            setOf("limiter", "limiterNote", "warmupMark"),
            gained.keys,
            "set_records gained something other than the reason, its note and the warm-up mark",
        )
        assertEquals("TEXT", gained.getValue("limiter").first, "limiter is not TEXT")
        assertEquals("TEXT", gained.getValue("limiterNote").first, "limiterNote is not TEXT")
        assertEquals("INTEGER", gained.getValue("warmupMark").first, "warmupMark is not an INTEGER")
        for ((name, spec) in gained) {
            val (_, notNull, default) = spec
            assertTrue(!notNull, "$name is NOT NULL, so its absent state cannot be stored")
            assertNull(default, "$name carries a default, which is an answer nobody gave")
        }
    }

    /**
     * Nothing that existed at v12 changed.
     *
     * The near neighbour of adding a column is retyping one beside it, and a
     * migration made of ADD COLUMN statements says nothing about the rest of
     * the table -- so a silently retyped column would reach Room's own
     * TableInfo check on a real phone and throw there instead of here. The
     * column most exposed to it on this hop is `warmup`, which sits beside the
     * new `warmupMark` and keeps its type, its NOT NULL and its meaning.
     */
    @Test
    fun `no column that existed at v12 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(12, table)
            val after = columnsOf(13, table)
            assertEquals(
                emptyList(),
                before.keys.filter { it !in after },
                "$table lost a column between v12 and v13",
            )
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v12",
            )
        }
    }

    /**
     * The migration executes exactly the three appends the baselines call for,
     * in order.
     *
     * Read off the real migration body through a recording database, so this
     * is the SQL that will run rather than a second copy of it kept beside the
     * first.
     */
    @Test
    fun `the migration runs three add-column statements and nothing else`() {
        assertEquals(
            listOf(
                "ALTER TABLE set_records ADD COLUMN limiter TEXT",
                "ALTER TABLE set_records ADD COLUMN limiterNote TEXT",
                "ALTER TABLE set_records ADD COLUMN warmupMark INTEGER",
            ),
            executedSql(),
        )
    }

    /**
     * Every statement is a plain append that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition, while every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history. A NOT NULL append is refused outright on a
     * populated table unless it carries a default; none of these is NOT NULL,
     * so none needs one, and the pin catches a later edit that adds the first
     * half without the second.
     */
    @Test
    fun `every statement is a plain append and none of them is destructive`() {
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * Nothing already recorded is given a reason or a purpose.
     *
     * Why a past set ended, and which past sets the lifter would have called
     * warm-ups, is recorded in no artifact this app has ever written. This is
     * the pin against a later "helpful" UPDATE -- writing `outside` onto every
     * pre-v13 failed set, say, which would be indistinguishable in the export
     * from an answer a lifter actually gave, and would be counted by the
     * grouping the column exists for.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a value nobody declared",
        )
    }
}
