package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v17 -> v18 migration: `liveReps` on set_records, what the sensor counted
 * while the set was being performed (#286).
 *
 * ## A NEW HOP, not an extension of 17
 *
 * v0.1.52 SHIPS `DATABASE_VERSION = 17`, read by
 * `git show v0.1.52:core/data/src/main/kotlin/com/macrophage/barspeed/data/AppDatabase.kt`
 * rather than assumed, so an installed build has run 16 -> 17 and extending
 * that hop would leave a device that already migrated without the new column.
 * [Migration16To17Test] states the opposite case and the same test: two columns
 * rode one hop there BECAUSE 17 had not shipped.
 *
 * ## Why a column at all, when the export word is derived
 *
 * The published `repsSource` word is NOT stored -- `RepsSourcePolicy` derives
 * it -- and this column is what makes the derivation possible. Two facts could
 * not be told apart from what v17 holds:
 *
 * 1. A LIFTER'S TALLY from a CORRECTION of a sensor count. `repsManual` is true
 *    in both cases; its own KDoc says so -- *"True when actualReps was entered
 *    or corrected by the lifter"* -- one column with two jobs.
 * 2. What the SENSOR counted on a set the lifter then corrected. The correction
 *    rewrites `actualReps`, so without this column the sensor's own figure is
 *    destroyed on exactly the sets where the sensor was wrong: the informative
 *    ones. Issue #286's field validation is the first deadlift session's hand
 *    count scored against the live count, so those sets are the whole point.
 *
 * Neither is recoverable later. The live count exists only while the set is
 * being performed: re-running the detector afterwards produces the BATCH
 * figure, which `LiveRepCall`'s own KDoc records as a different number over a
 * different estimate, and the app's cue track carries the spoken calls only
 * when audio cues were switched on.
 *
 * ## The shape
 *
 * INTEGER, NULLABLE, NO DEFAULT. Nullable because every row written before v18
 * was recorded by a build that stored no live count, and no value can be
 * invented for them. NO DEFAULT because a defaulted 0 would say the sensor
 * counted zero reps on every set in the archive -- absence rendered as a value,
 * and the one reading that makes the export word lie.
 *
 * ## What this verifies, exactly
 *
 * [Migration16To17Test]'s instrument, one hop later, and that file states the
 * method: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the DIFFERENCE
 * between `schemas/.../17.json` and `schemas/.../18.json`, both generated by the
 * Room compiler from the entities rather than written by hand. Nothing here
 * executes SQL -- there is no SQLite on this module's test classpath and no
 * `androidTest` source set anywhere -- so this cannot say that SQLite accepts
 * the statement, that a real file survives it, or that Room's own `TableInfo`
 * check passes afterwards. A bench run against the emulator is owed for those.
 */
class Migration17To18Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_17_18.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration16To17Test] the way that file took it from its predecessor: a
     * constant left behind at 17 ships a build whose schema the chain cannot
     * reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on eighteen`() {
        assertEquals(18, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(18, declaredVersion(18), "18.json does not describe version 18")
        assertEquals(17, declaredVersion(17), "17.json does not describe version 17")
        assertEquals(17, AppDatabase.MIGRATION_17_18.startVersion)
        assertEquals(18, AppDatabase.MIGRATION_17_18.endVersion)
    }

    /**
     * v18 differs from v17 by exactly one nullable INTEGER column on
     * set_records.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a second column, a retyped column and a
     * dropped one are all caught -- none of which the statement below would
     * carry.
     */
    @Test
    fun `the schema baselines differ by exactly the live rep count`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(18, table) - columnsOf(17, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(18, "set_records") - columnsOf(17, "set_records").keys
        assertEquals(setOf("liveReps"), gained.keys, "set_records gained something other than the live rep count")
        val (affinity, notNull, default) = gained.getValue("liveReps")
        assertEquals("INTEGER", affinity, "liveReps is not INTEGER, so it cannot hold a rep count")
        assertTrue(!notNull, "liveReps is NOT NULL, so a set no live counter ran on cannot be stored")
        assertNull(default, "liveReps carries a default, which is a count nothing counted")
    }

    /**
     * Nothing that existed at v17 changed -- and the two rep columns above all.
     *
     * The near neighbour of adding this column is retyping the ones it explains.
     * `actualReps` keeps its type, its nullability and its default, and so does
     * `repsManual`: the derived export word reads all three, so a silently
     * retyped column would change what the word means rather than failing
     * loudly.
     */
    @Test
    fun `no column that existed at v17 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(17, table)
            val after = columnsOf(18, table)
            assertEquals(emptyList(), before.keys.filter { it !in after }, "$table lost a column between v17 and v18")
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v17",
            )
        }
        val v18 = columnsOf(18, "set_records")
        assertEquals(Triple("INTEGER", true, null), v18.getValue("actualReps"), "actualReps changed shape")
        assertEquals(Triple("INTEGER", true, null), v18.getValue("repsManual"), "repsManual changed shape")
    }

    /** The migration executes exactly the one append the baselines call for. */
    @Test
    fun `the migration runs one add-column statement and nothing else`() {
        assertEquals(listOf("ALTER TABLE set_records ADD COLUMN liveReps INTEGER"), executedSql())
    }

    /**
     * A plain append that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition, while every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history.
     */
    @Test
    fun `the statement is a plain append and is not destructive`() {
        assertTrue(executedSql().isNotEmpty(), "the migration executes nothing at all")
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is given a live count.
     *
     * There is nothing to backfill FROM. The live count exists only while the
     * set is being performed; re-running the detector over a stored stream
     * produces the BATCH figure, which is a different number over a different
     * velocity estimate. Writing that figure here would state that the lifter
     * heard a count the app never spoke, and the export word would then read
     * `sensor` on sets recorded by a build that had no live counter.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a count nothing counted",
        )
    }

    /**
     * The hop is REGISTERED, which the statements above cannot say.
     *
     * A migration declared and not passed to `addMigrations` is a migration
     * Room never runs, and the failure lands on the lifter's phone as an
     * `IllegalStateException` on open. Read off the declared list rather than
     * off `build`, which needs a `Context`.
     */
    @Test
    fun `the hop is in the chain the database is built with`() {
        assertEquals(
            (1..17).map { it to it + 1 },
            AppDatabase.MIGRATIONS.map { it.startVersion to it.endVersion },
            "the migration chain is not an unbroken 1 -> 18",
        )
    }
}
