package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v15 -> v16 migration: `voided` and `voidReason` on set_records -- the
 * mark that says the lifter did not perform this set, and optionally why
 * (#60).
 *
 * DIFFERENTIALS. Five of the six tests here fail at the commit that introduces
 * them. There is no committed `16.json`, so the baseline lookup errors out
 * with the message it was written to carry; [DATABASE_VERSION] is 15; and
 * [AppDatabase.MIGRATION_15_16] was declared with an empty body and left
 * unregistered by the commit before this one, so the recording database sees
 * no statement at all.
 *
 * The sixth, `the migration writes no value into any existing row`, passes
 * here because the body is empty. It is kept for what it will catch: the
 * backfill this hop must refuse, described below.
 *
 * ## What this verifies, exactly
 *
 * [Migration14To15Test]'s instrument, one hop later, and the file two hops
 * back states the method: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the
 * DIFFERENCE between `schemas/.../15.json` and `schemas/.../16.json`, both
 * generated by the Room compiler from the entities rather than written by
 * hand. Nothing here executes SQL -- there is no SQLite on this module's test
 * classpath and no `androidTest` source set anywhere -- so this cannot say
 * that SQLite accepts the statements, that a real file survives them, that
 * Room's own `TableInfo` check passes afterwards, or that the hop was
 * registered at all. The emulator exercise that says those things is recorded
 * in the body of the commit that fills the migration.
 *
 * ## The two shapes, and why they differ from each other
 *
 * `voided` is NOT NULL, appended WITH `DEFAULT 0` IN THE SQL, which is
 * [Migration11To12Test]'s shape and deliberately not [Migration13To14Test]'s
 * nullable append. The mark is a statement the lifter makes about a set; a set
 * they have not marked is a set they performed, and there is no third state
 * for the column to hold. That
 * `0` is also an ambiguity and it is stated rather than hidden, exactly as
 * `added` states its own: every row written before v16 reads false, and a set
 * an earlier build recorded that the lifter never performed is
 * indistinguishable from one they did. The mark is available on those rows
 * from this version on, which is the whole point of the change -- what cannot
 * be recovered is a mark nobody was able to make. The default lives in the
 * STATEMENT and not in the entity: Room writes `defaultValue` into the
 * committed schema only for an `@ColumnInfo(defaultValue = …)`, and `added`,
 * `warmup`, `failed` and `repsManual` are all `INTEGER NOT NULL DEFAULT 0` in
 * their migrations while carrying no entity-side default at all -- so the
 * baseline assertion below is `assertNull`, and a `DEFAULT` appearing there
 * would mean the entity had grown one the SQL does not match.
 *
 * `voidReason` is NULLABLE WITH NO DEFAULT, which is the opposite shape one
 * column over, for the reason [Migration13To14Test] gives for `plannedSide`:
 * the reason is optional on a voided set and meaningless on an unvoided one,
 * so null is a real state that no value stands for. A default here would put
 * words in the lifter's mouth on every row in the database.
 *
 * ## The backfill that is refused
 *
 * `UPDATE set_records SET voided = 1 WHERE actualDurationS = 0 AND failed = 1`
 * would mark field-37 set 13 -- the row this whole change exists for -- and it
 * is refused. A 0-second failed timed set is not evidence that the set did not
 * happen: a lifter who unracks, fails immediately and taps failed produces the
 * same row, and #216's abandoned-in-lead-in set is a third case. v15's
 * `workBegan` separates that third case on rows written FROM v15 ON and on no
 * others: it is null on every row this migration would sweep, field-37 set 13
 * among them, so it distinguishes nothing a backfill could read. Which of the
 * three a past row is cannot be read from anything stored, and the void mark
 * is the LIFTER'S statement. A migration that
 * guessed it would be indistinguishable, in the export, from a statement they
 * made -- and it would silently drop real sets out of the volume figure.
 */
class Migration15To16Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test.schema]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_15_16.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration14To15Test] the way that file took it from
     * [Migration13To14Test]: a constant left behind at 15 ships a build whose
     * schema the chain cannot reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on sixteen`() {
        assertEquals(16, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(16, declaredVersion(16), "16.json does not describe version 16")
        assertEquals(15, declaredVersion(15), "15.json does not describe version 15")
        assertEquals(15, AppDatabase.MIGRATION_15_16.startVersion)
        assertEquals(16, AppDatabase.MIGRATION_15_16.endVersion)
    }

    /**
     * v16 differs from v15 by exactly the void mark and its reason.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a third column, a retyped column and a
     * dropped one are all caught -- none of which the two statements below
     * would carry.
     */
    @Test
    fun `the schema baselines differ by exactly the void mark and its reason`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(16, table) - columnsOf(15, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(16, "set_records") - columnsOf(15, "set_records").keys
        assertEquals(
            setOf("voided", "voidReason"),
            gained.keys,
            "set_records gained something other than the void mark and its reason",
        )
        val (markAffinity, markNotNull, markDefault) = gained.getValue("voided")
        assertEquals("INTEGER", markAffinity, "voided is not an INTEGER, so it cannot hold a boolean")
        assertTrue(markNotNull, "voided is nullable, which invents a third state the mark does not have")
        assertNull(markDefault, "voided carries an entity-side default the migration's DEFAULT 0 would have to match")
        val (reasonAffinity, reasonNotNull, reasonDefault) = gained.getValue("voidReason")
        assertEquals("TEXT", reasonAffinity, "voidReason is not TEXT, so it cannot hold the lifter's words")
        assertTrue(!reasonNotNull, "voidReason is NOT NULL, so a set voided without a reason cannot be stored")
        assertNull(reasonDefault, "voidReason carries a default, which puts words in the lifter's mouth")
    }

    /**
     * Nothing that existed at v15 changed -- and `failed` above all.
     *
     * The near neighbour of adding a mark is quietly redefining the flag it
     * sits beside. `failed` keeps its type, its nullability and its default
     * here: a voided set may still be marked failed, and the two facts stay
     * apart, the way `warmup` and `warmupMark` are kept apart one column over.
     * A migration made of ADD COLUMN statements says nothing about the rest of
     * the table, so a silently retyped column would reach Room's own TableInfo
     * check on a real phone and throw there instead of here.
     */
    @Test
    fun `no column that existed at v15 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(15, table)
            val after = columnsOf(16, table)
            assertEquals(
                emptyList(),
                before.keys.filter { it !in after },
                "$table lost a column between v15 and v16",
            )
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v15",
            )
        }
        assertEquals(
            Triple("INTEGER", true, null),
            columnsOf(16, "set_records").getValue("failed"),
            "failed changed shape, and it is the flag a voided set is most likely to carry",
        )
    }

    /**
     * The migration executes exactly the two appends the baselines call for.
     *
     * Read off the real migration body through a recording database, so this
     * is the SQL that will run rather than a second copy of it kept beside the
     * first.
     */
    @Test
    fun `the migration runs two add-column statements and nothing else`() {
        assertEquals(
            listOf(
                "ALTER TABLE set_records ADD COLUMN voided INTEGER NOT NULL DEFAULT 0",
                "ALTER TABLE set_records ADD COLUMN voidReason TEXT",
            ),
            executedSql(),
        )
    }

    /**
     * The statements are plain appends that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition, while every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history.
     *
     * The count is asserted first and on purpose: a `for` loop over an empty
     * list passes every assertion inside it, so without the count this test
     * would report green against a migration that does nothing at all.
     */
    @Test
    fun `the statements are plain appends and are not destructive`() {
        val statements = executedSql()
        assertEquals(2, statements.size, "the migration does not run the two appends this hop is made of")
        for (sql in statements) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is marked.
     *
     * The pin against the backfill this file's KDoc refuses. Marking every
     * 0-second failed timed set would mark field-37 set 13 and would also mark
     * a set the lifter unracked, failed instantly and tapped -- and it would
     * take those sets out of the volume figure without anyone saying they did
     * not happen. The void mark is the lifter's statement, and a migration
     * cannot make it for them.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration marks rows nobody marked",
        )
    }
}
