package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v13 -> v14 migration: `plannedSide` on set_records, the side the PLAN
 * prescribed, frozen beside the side the lifter worked (#215, #144).
 *
 * DIFFERENTIALS. Every test here fails at the commit that introduces it. There
 * is no committed `14.json`, so the baseline lookup errors out with the
 * message it was written to carry; [DATABASE_VERSION] is 13; and
 * [AppDatabase.MIGRATION_13_14] is declared with an empty body and is not
 * registered, so the recording database sees no statement at all.
 *
 * ## What this verifies, exactly
 *
 * [Migration12To13Test]'s instrument, one hop later, and that file states the
 * method: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the
 * DIFFERENCE between `schemas/.../13.json` and `schemas/.../14.json`, both
 * generated by the Room compiler from the entities rather than written by
 * hand. Nothing here executes SQL -- there is no SQLite on this module's test
 * classpath and no `androidTest` source set anywhere -- so this cannot say
 * that SQLite accepts the statement, that a real file survives it, or that
 * Room's own `TableInfo` check passes afterwards.
 *
 * ## The emulator exercise that does say it
 *
 * Run on AVD `barspeed-api35` and recorded in the body of `13ecc3a6`, subject
 * "Record the 13 to 14 emulator run where the hop's own test points at it". A
 * debug build of `d39e12eb` -- an earlier commit on this branch, subject "Keep
 * the grid's one-decision promise, and delete three more false claims", where
 * `DATABASE_VERSION` is still 13 -- wrote a real ad-hoc set, and the v14 build
 * was installed over it with
 * `adb install -r`. After it: `PRAGMA user_version` reads 14, the row survives
 * with `side` = "left" and `plannedSide` NULL, and `.schema set_records` shows
 * `plannedSide TEXT` appended UNQUOTED at the end of the table -- the raw
 * `ALTER TABLE` signature, which is what distinguishes a migration from Room
 * recreating the table. A plan session then recorded three sets and published
 * `plannedSide` in a document declaring 1.17. Downgrading back to the v13
 * build raised the rescue card rather than wiping anything.
 *
 * None of that is executed by CI, and none of it is re-run by this file.
 *
 * ## The shape, and why it is this one
 *
 * NULLABLE WITH NO DEFAULT, which is [Migration12To13Test]'s shape and
 * deliberately not [Migration11To12Test]'s defaulted NOT NULL append. The
 * column has a real absent state that no value stands for -- bilateral work,
 * an ad-hoc set, an appended set, and every row written before v14 -- and a
 * default would store a prescription nobody wrote.
 *
 * ## The backfill that is refused, and why it looks so nearly right
 *
 * On every row written before v14, `side` WAS the plan's prescription: nothing
 * in the app could record a deviation, which is what #144 was opened to say.
 * So `UPDATE set_records SET plannedSide = side` would be true of the plan and
 * false about the lifter -- it would assert of every historical set that the
 * app knew which limb moved. That is the same refusal every migration since v8
 * has written down, and here it is the sharper one, because the wrong answer
 * is available and plausible.
 */
class Migration13To14Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test.schema]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_13_14.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration12To13Test] the way that file took it from
     * [Migration11To12Test]: a constant left behind at 13 ships a build whose
     * schema the chain cannot reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on fourteen`() {
        assertEquals(14, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(14, declaredVersion(14), "14.json does not describe version 14")
        assertEquals(13, declaredVersion(13), "13.json does not describe version 13")
        assertEquals(13, AppDatabase.MIGRATION_13_14.startVersion)
        assertEquals(14, AppDatabase.MIGRATION_13_14.endVersion)
    }

    /**
     * v14 differs from v13 by exactly one nullable column on set_records.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a second column, a retyped column and a
     * dropped one are all caught -- none of which the single statement below
     * would carry.
     */
    @Test
    fun `the schema baselines differ by exactly the prescribed-side column`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(14, table) - columnsOf(13, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(14, "set_records") - columnsOf(13, "set_records").keys
        assertEquals(
            setOf("plannedSide"),
            gained.keys,
            "set_records gained something other than the prescribed side",
        )
        val (affinity, notNull, default) = gained.getValue("plannedSide")
        assertEquals("TEXT", affinity, "plannedSide is not TEXT, so it cannot hold the plan's own word")
        assertTrue(!notNull, "plannedSide is NOT NULL, so a set nobody prescribed one for cannot be stored")
        assertNull(default, "plannedSide carries a default, which is a prescription nobody wrote")
    }

    /**
     * Nothing that existed at v13 changed -- and `side` above all.
     *
     * The near neighbour of adding a column is retyping the one it pairs with.
     * `side` keeps its type and its nullability here; what changes is what the
     * app WRITES into it, which is a decision in `:app` and `:core:model` and
     * not a schema move. A migration made of ADD COLUMN statements says
     * nothing about the rest of the table, so a silently retyped column would
     * reach Room's own TableInfo check on a real phone and throw there instead
     * of here.
     */
    @Test
    fun `no column that existed at v13 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(13, table)
            val after = columnsOf(14, table)
            assertEquals(
                emptyList(),
                before.keys.filter { it !in after },
                "$table lost a column between v13 and v14",
            )
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v13",
            )
        }
        assertEquals(
            Triple("TEXT", false, null),
            columnsOf(14, "set_records").getValue("side"),
            "side changed shape, and it is the column this hop pairs with",
        )
    }

    /**
     * The migration executes exactly the one append the baselines call for.
     *
     * Read off the real migration body through a recording database, so this
     * is the SQL that will run rather than a second copy of it kept beside the
     * first.
     */
    @Test
    fun `the migration runs one add-column statement and nothing else`() {
        assertEquals(
            listOf("ALTER TABLE set_records ADD COLUMN plannedSide TEXT"),
            executedSql(),
        )
    }

    /**
     * The statement is a plain append that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition, while every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history.
     */
    @Test
    fun `the statement is a plain append and is not destructive`() {
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is given a prescription.
     *
     * The pin against the backfill this file's KDoc refuses: copying `side`
     * into `plannedSide` on every pre-v14 row would be indistinguishable, in
     * the export, from a prescription the app had actually recorded, and every
     * one of those rows would then read as a set worked exactly as planned by
     * an app that could not tell.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a prescription nobody wrote",
        )
    }
}
