package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The v19 -> v20 migration: five nullable columns on `set_records` -- the
 * working targets a set ran against (`workingReps`, `workingDurationS`,
 * `workingLoadKg`), the plan's frozen tempo (`plannedTempo`), and the instant
 * the rest after the set runs from (`restStartedAtMs`). Issue #157.
 *
 * ## A NEW HOP, not an extension of 19
 *
 * v0.1.54 SHIPS `DATABASE_VERSION = 19`, read by
 * `git show v0.1.54:core/data/src/main/kotlin/com/macrophage/barspeed/data/AppDatabase.kt`
 * rather than assumed, so an installed build has run 18 -> 19 and extending
 * that hop would leave a phone that already migrated without the columns.
 *
 * ## Why the columns at all
 *
 * `RecordViewModel.endSet` computes the working rep count and hold -- the
 * figures every judgement reads -- and until v20 dropped both at the write, so
 * a row could show what the plan asked and what happened and never the target
 * the set was judged against. With the in-app buttons raising a floor plan's
 * load or reps on a set that shows headroom, "planned" and "working" differ by
 * design, and an archive that holds only the first reads a met raised target
 * as an over-performance and a met lowered one as a miss.
 *
 * ## What this verifies, exactly
 *
 * [Migration18To19Test]'s instrument, one hop later: the real migration body
 * runs against a recording `SupportSQLiteDatabase`, and what it executes is
 * compared with the DIFFERENCE between `schemas/.../19.json` and
 * `schemas/.../20.json`, both generated by the Room compiler from the entities
 * rather than written by hand. Nothing here executes SQL -- there is no SQLite
 * on this module's test classpath and no `androidTest` source set anywhere --
 * so this cannot say that SQLite accepts the statements, that a real file
 * survives them, or that Room's own `TableInfo` check passes afterwards. The
 * two-way emulator exercise at the cut is owed for those.
 *
 * NOT A DIFFERENTIAL. Every test here passes at the commit that adds it, which
 * also adds the hop: a declared-and-unregistered hop fails on the lifter's
 * phone rather than anywhere a test can see it, so the migration and its pins
 * arrive together.
 */
class Migration19To20Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_19_20.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration18To19Test] the way that file took it from its predecessor: a
     * constant left behind at 19 ships a build whose schema the chain cannot
     * reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on twenty`() {
        assertEquals(20, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(20, declaredVersion(20), "20.json does not describe version 20")
        assertEquals(19, declaredVersion(19), "19.json does not describe version 19")
        assertEquals(19, AppDatabase.MIGRATION_19_20.startVersion)
        assertEquals(20, AppDatabase.MIGRATION_19_20.endVersion)
    }

    /**
     * v20 differs from v19 by exactly the five set_records columns, each
     * nullable with no default, each with the affinity its Kotlin type implies.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a sixth column, a retyped column and a dropped
     * one are all caught.
     */
    @Test
    fun `the schema baselines differ by exactly the five working and rest columns`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(20, table) - columnsOf(19, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(20, "set_records") - columnsOf(19, "set_records").keys
        assertEquals(
            mapOf(
                "workingReps" to Triple("INTEGER", false, null),
                "workingDurationS" to Triple("INTEGER", false, null),
                "workingLoadKg" to Triple("REAL", false, null),
                "plannedTempo" to Triple("TEXT", false, null),
                "restStartedAtMs" to Triple("INTEGER", false, null),
            ),
            gained,
            "set_records gained something other than the five nullable, defaultless columns",
        )
    }

    /** Nothing that existed at v19 changed its type, nullability or default. */
    @Test
    fun `no column that existed at v19 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(19, table)
            val after = columnsOf(20, table)
            assertEquals(emptyList(), before.keys.filter { it !in after }, "$table lost a column between v19 and v20")
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v19",
            )
        }
    }

    /**
     * The migration executes exactly the five appends the baselines call for,
     * and nothing else. Asserted as a whole list so a sixth statement, or a
     * missing one, cannot pass unnoticed.
     */
    @Test
    fun `the migration runs the five add-column statements and nothing else`() {
        assertEquals(
            listOf(
                "ALTER TABLE set_records ADD COLUMN workingReps INTEGER",
                "ALTER TABLE set_records ADD COLUMN workingDurationS INTEGER",
                "ALTER TABLE set_records ADD COLUMN workingLoadKg REAL",
                "ALTER TABLE set_records ADD COLUMN plannedTempo TEXT",
                "ALTER TABLE set_records ADD COLUMN restStartedAtMs INTEGER",
            ),
            executedSql(),
        )
    }

    /**
     * Plain appends that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table definition,
     * while every form Room would generate for a table recreate copies rows --
     * which on this schema means copying every gzipped IMU blob in the lifter's
     * history.
     */
    @Test
    fun `the statements are plain appends and are not destructive`() {
        assertTrue(executedSql().isNotEmpty(), "the migration executes nothing at all")
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue("NOT NULL" !in sql.uppercase(), "a working target is not always present: $sql")
            assertTrue("DEFAULT" !in sql.uppercase(), "a default answers for every set already recorded: $sql")
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is given a working target.
     *
     * The obvious backfill -- `workingReps = plannedReps` -- is the #157 defect
     * itself: it states that the plan's count ran on every set the lifter
     * changed with the in-app buttons. A null on an old row says the build that
     * recorded it could not say, which is the truth.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a target nobody recorded",
        )
    }

    /**
     * The chain is unbroken from 1 to the compiled version, which the
     * statements above cannot say.
     *
     * A migration declared and not passed to `addMigrations` is a migration Room
     * never runs, and the failure lands on the lifter's phone as an
     * `IllegalStateException` on open. The whole-chain equality moved here from
     * [Migration18To19Test] with the newest hop, for the reason the constant
     * did.
     */
    @Test
    fun `the hop is in the chain the database is built with`() {
        assertEquals(
            (1..19).map { it to it + 1 },
            AppDatabase.MIGRATIONS.map { it.startVersion to it.endVersion },
            "the migration chain is not an unbroken 1 -> 20",
        )
    }
}
