package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v16 -> v17 migration: `bodyWeightKg` on set_records, the term the load
 * arithmetic added and the archive never published (#220).
 *
 * DIFFERENTIALS. Every test here fails at the commit that introduces it. There
 * is no committed `17.json`, so the baseline lookup errors out with the message
 * it was written to carry; [DATABASE_VERSION] is 16; and
 * [AppDatabase.MIGRATION_16_17] is declared with an empty body and is not
 * registered, so the recording database sees no statement at all.
 *
 * ## Why a column and not a derivation
 *
 * `SetLoadPolicy.totalKg` returns `bodyWeightKg + addedKg` on a body-weight
 * set, so on field-37 (app 0.1.48) six of thirteen loads have the lifter's own
 * mass as their LARGEST term, and neither `session.json` nor `meta.json` names
 * it. The sum alone is recoverable; the split is not. It cannot be recovered
 * later either: the app stores exactly one body weight, in `SettingsStore`,
 * and it moves -- reading it at export time would answer with today's figure
 * for a set recorded in March. Nor is the ADDED load stored anywhere on the
 * row, so the pair cannot be reconstructed from what v16 holds.
 *
 * ## What this verifies, exactly
 *
 * [Migration14To15Test]'s instrument, two hops later, and that file states the
 * method: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the DIFFERENCE
 * between `schemas/.../16.json` and `schemas/.../17.json`, both generated by
 * the Room compiler from the entities rather than written by hand. Nothing here
 * executes SQL -- there is no SQLite on this module's test classpath and no
 * `androidTest` source set anywhere -- so this cannot say that SQLite accepts
 * the statement, that a real file survives it, that Room's own `TableInfo`
 * check passes afterwards, or that the hop was REGISTERED at all.
 *
 * ## The shape, and why it is this one
 *
 * NULLABLE WITH NO DEFAULT, [Migration14To15Test]'s shape. Every row written
 * before v17 was recorded by a build that stored no body weight per set, and a
 * REAL zero is a distinct state the app can reach today: `totalKg` treats a
 * null body weight as 0 kg (#61), so a body-weight set recorded before any
 * body weight was entered has a genuine 0 kg term. A defaulted 0 would make
 * those two indistinguishable, and would assert of the whole archive that the
 * lifter weighed nothing.
 *
 * ## The backfill that is refused
 *
 * `SettingsStore`'s body weight is the obvious candidate. It is refused: it is
 * TODAY's weight, it carries no history, and writing it across the archive
 * would state that every past body-weight set was recorded at the lifter's
 * current mass -- the precise false claim the export gap already lets a reader
 * make by accident. #199 tracks the freshness of that one figure, and nothing
 * anywhere records what it was on a past date.
 */
class Migration16To17Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_16_17.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration15To16Test] the way that file took it from its predecessor: a
     * constant left behind at 16 ships a build whose schema the chain cannot
     * reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on seventeen`() {
        assertEquals(17, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(17, declaredVersion(17), "17.json does not describe version 17")
        assertEquals(16, declaredVersion(16), "16.json does not describe version 16")
        assertEquals(16, AppDatabase.MIGRATION_16_17.startVersion)
        assertEquals(17, AppDatabase.MIGRATION_16_17.endVersion)
    }

    /**
     * v17 differs from v16 by exactly one nullable REAL column on set_records.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a second column, a retyped column and a
     * dropped one are all caught -- none of which the statement below would
     * carry.
     */
    @Test
    fun `the schema baselines differ by exactly the body-weight column`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(17, table) - columnsOf(16, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(17, "set_records") - columnsOf(16, "set_records").keys
        assertEquals(setOf("bodyWeightKg"), gained.keys, "set_records gained something other than the body weight")
        val (affinity, notNull, default) = gained.getValue("bodyWeightKg")
        assertEquals("REAL", affinity, "bodyWeightKg is not REAL, so it cannot hold a kilogram figure")
        assertTrue(!notNull, "bodyWeightKg is NOT NULL, so a row the app could not observe cannot be stored")
        assertNull(default, "bodyWeightKg carries a default, which is a weighing nobody did")
    }

    /**
     * Nothing that existed at v16 changed -- and `loadKg` above all.
     *
     * The near neighbour of adding this column is retyping the one it explains.
     * `loadKg` keeps its type, its nullability and its default; what changes is
     * that a second column now says how much of it was the lifter. A migration
     * made of ADD COLUMN statements says nothing about the rest of the table,
     * so a silently retyped column would reach Room's own TableInfo check on a
     * real phone and throw there instead of here.
     */
    @Test
    fun `no column that existed at v16 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(16, table)
            val after = columnsOf(17, table)
            assertEquals(emptyList(), before.keys.filter { it !in after }, "$table lost a column between v16 and v17")
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v16",
            )
        }
        val v17 = columnsOf(17, "set_records")
        assertEquals(Triple("REAL", true, null), v17.getValue("loadKg"), "loadKg changed shape")
        assertEquals(Triple("REAL", false, null), v17.getValue("plannedLoadKg"), "plannedLoadKg changed shape")
    }

    /**
     * The migration executes exactly the one append the baselines call for.
     *
     * Read off the real migration body through a recording database, so this is
     * the SQL that will run rather than a second copy of it kept beside the
     * first.
     */
    @Test
    fun `the migration runs one add-column statement and nothing else`() {
        assertEquals(listOf("ALTER TABLE set_records ADD COLUMN bodyWeightKg REAL"), executedSql())
    }

    /**
     * A plain append that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition, while every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history.
     */
    @Test
    fun `the statement is a plain append and is not destructive`() {
        assertTrue(executedSql().isNotEmpty(), "the migration executes nothing at all")
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is given a weighing.
     *
     * The pin against the backfill this file's KDoc refuses. The settings store
     * holds today's figure with no history, so copying it across the archive
     * would state that every past body-weight set was recorded at the lifter's
     * current mass -- indistinguishable, in the export, from a figure the app
     * had actually recorded at the time.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a weighing nobody did",
        )
    }
}
