package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v11 -> v12 migration, read against Room's own committed descriptions of
 * the two schemas.
 *
 * ## What this does and does not verify, exactly
 *
 * [Migration10To11Test]'s instrument, one hop later, and its KDoc states the
 * method once: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the DIFFERENCE
 * between `schemas/…/11.json` and `schemas/…/12.json`, both generated by the
 * Room compiler from the entities rather than written by hand. Nothing here
 * executes SQL -- there is no SQLite on this module's test classpath and no
 * `androidTest` source set anywhere -- so this cannot say that SQLite accepts
 * the statement, that a real file survives it, or that Room's own `TableInfo`
 * check passes afterwards.
 *
 * WHY THIS HOP DIFFERS FROM THE LAST ONE, and the difference is the whole
 * reason this is a separate file rather than three more assertions in that one.
 * v10 -> v11 appends three NULLABLE columns with no default, and its tests
 * assert exactly that -- `assertTrue(!notNull)`, `assertNull(default)`, and
 * `"NOT NULL" !in sql`. This hop appends a NON-NULL column WITH a default,
 * because `SetRecordEntity.added` is a non-null `Boolean` and SQLite refuses a
 * NOT NULL append with no default on a populated table. Widening the older
 * file's assertions to admit both shapes would have destroyed what they say:
 * a nullable append and a defaulted non-null one fail in different directions,
 * and an assertion that accepts either cannot catch a column declared the
 * wrong way round.
 *
 * THE SHAPE HAS PRECEDENT IN THIS SCHEMA. `failed` (v4), `warmup` (v5) and
 * `repsManual` (v7) are all `INTEGER NOT NULL DEFAULT 0` in their migrations
 * and all carry `notNull: true` with NO `defaultValue` in the committed
 * descriptions -- the same asymmetry this column has, verified by reading
 * 11.json rather than assumed. Room's `TableInfo` comparison ignores the
 * database-side default when the entity declares none, which is why those three
 * have shipped across eight version bumps without throwing. That is a statement
 * about Room's comparison read off this repository's own shipped history, not a
 * claim that this migration has been executed: it has not.
 *
 * A CORRECTION, named rather than reworded around. This KDoc read "The two-way
 * emulator exercise for the v0.1.44 cluster covers BOTH bumps together. v0.1.44
 * has not been cut, so no stock install carries 11 either -- a phone upgrading
 * to this build runs 10 -> 11 -> 12 back to back." It was true when written and
 * is false now: v0.1.44 WAS cut, at tag
 * `7cf6e8c3cc546ab8d64c9fb2be86de2129250b43`, whose `AppDatabase.kt` reads
 * `DATABASE_VERSION = 12`. This hop has therefore SHIPPED. The exercise it was
 * waiting for was run for the v0.1.44 cut; what is owed now is the exercise for
 * 12 -> 13, which is [Migration12To13Test]'s to name and no commit before that
 * one discharges.
 */
class Migration11To12Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test.schema]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_11_12.migrate(recorder)
        return executed
    }

    /**
     * The committed baseline and the migration's own endpoints are one number,
     * and the compiled version is at or beyond it.
     *
     * THE MIDDLE ASSERTION USED TO READ `assertEquals(12, DATABASE_VERSION)`,
     * and it is corrected here exactly as [Migration10To11Test]'s was one hop
     * earlier, for the same reason and by the same rule: it was true while 12
     * was the newest hop and went false the moment #189 added a thirteenth. An
     * intermediate hop's end version is not the compiled version and never
     * was, and asserting they are equal reds this file on every future bump
     * for no defect. What the hop genuinely owes the constant is that the
     * chain still reaches it. The equality itself is not dropped -- it moves
     * to the newest hop, in [Migration12To13Test].
     *
     * The exact-12 assertions below are untouched. An entity changed with this
     * migration left behind still ships a build whose schema the chain cannot
     * produce, and Room throws on the lifter's phone.
     */
    @Test
    fun `the committed baseline and the migration agree on twelve, within a chain that reaches the compiled version`() {
        assertTrue(
            AppDatabase.MIGRATION_11_12.endVersion <= DATABASE_VERSION,
            "this migration ends beyond DATABASE_VERSION, so the chain overshoots the schema this build compiles",
        )
        assertEquals(12, declaredVersion(12), "12.json does not describe version 12")
        assertEquals(11, declaredVersion(11), "11.json does not describe version 11")
        assertEquals(11, AppDatabase.MIGRATION_11_12.startVersion)
        assertEquals(12, AppDatabase.MIGRATION_11_12.endVersion)
    }

    /**
     * v12 differs from v11 by exactly one column: a NOT NULL INTEGER on
     * set_records, carrying no entity-side default.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a second column, a retyped column and a
     * dropped one are all caught -- none of which the single statement below
     * would carry.
     */
    @Test
    fun `the schema baselines differ by exactly the added flag on set_records`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(12, table) - columnsOf(11, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(12, "set_records") - columnsOf(11, "set_records").keys
        assertEquals(setOf("added"), gained.keys, "set_records gained something other than added")
        val (affinity, notNull, default) = gained.getValue("added")
        assertEquals("INTEGER", affinity, "added is not an INTEGER, so the migration's column type is wrong")
        assertTrue(notNull, "added is nullable, which a non-null Kotlin Boolean cannot produce")
        assertNull(default, "added carries an entity-side default the migration's DEFAULT 0 would have to match")
    }

    /**
     * Nothing that existed at v11 changed.
     *
     * The near neighbour of adding a column is retyping one beside it, and a
     * migration made of ADD COLUMN statements says nothing about the rest of
     * the table -- so a silently retyped column would reach Room's own
     * TableInfo check on a real phone and throw there instead of here.
     */
    @Test
    fun `no column that existed at v11 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(11, table)
            val after = columnsOf(12, table)
            assertEquals(
                emptyList(),
                before.keys.filter { it !in after },
                "$table lost a column between v11 and v12",
            )
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v11",
            )
        }
    }

    /**
     * The migration executes exactly one statement, and it is the append the
     * baselines call for.
     *
     * Read off the real migration body through a recording database, so this is
     * the SQL that will run rather than a second copy of it kept beside the
     * first.
     */
    @Test
    fun `the migration runs one add-column statement and nothing else`() {
        assertEquals(
            listOf("ALTER TABLE set_records ADD COLUMN added INTEGER NOT NULL DEFAULT 0"),
            executedSql(),
        )
    }

    /**
     * The statement cannot rewrite the table, and its NOT NULL is paired with a
     * default so a populated table accepts it.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition; a NOT NULL column WITHOUT a default is refused outright on a
     * non-empty table, and every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history. So the pairing asserted here is not a stylistic
     * preference: unpaired, this migration throws on the first phone that has
     * ever recorded a set, and paired, it is the cheapest correct statement and
     * the only one that cannot lose a row.
     */
    @Test
    fun `the not-null append carries the default that lets a populated table take it`() {
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * Nothing already recorded is marked as appended.
     *
     * The default SQLite writes into existing rows is 0, which is the same
     * claim the column's own KDoc makes: which past sets were improvised is
     * recorded in no artifact this app has ever written, so any other value
     * would be invented outright. This is the pin against a later "helpful"
     * UPDATE -- guessing from a null `plannedReps`, say, which is also what an
     * ad-hoc set and a plan block written without rep targets both look like.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills a value nobody declared",
        )
    }
}
