package com.macrophage.barspeed.data

import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.lang.reflect.Proxy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The v14 -> v15 migration: `workBegan` and `failedByLifter` on set_records,
 * the two capture facts an export needs before it can stop fabricating (#216).
 *
 * DIFFERENTIALS. Every test here fails at the commit that introduces it. There
 * is no committed `15.json`, so the baseline lookup errors out with the
 * message it was written to carry; [DATABASE_VERSION] is 14; and
 * [AppDatabase.MIGRATION_14_15] is declared with an empty body and is not
 * registered, so the recording database sees no statement at all.
 *
 * ## What this verifies, exactly
 *
 * [Migration13To14Test]'s instrument, one hop later, and that file states the
 * method: the real migration body runs against a recording
 * `SupportSQLiteDatabase`, and what it executes is compared with the
 * DIFFERENCE between `schemas/.../14.json` and `schemas/.../15.json`, both
 * generated by the Room compiler from the entities rather than written by
 * hand. Nothing here executes SQL -- there is no SQLite on this module's test
 * classpath and no `androidTest` source set anywhere -- so this cannot say
 * that SQLite accepts the statements, that a real file survives them, that
 * Room's own `TableInfo` check passes afterwards, or that the hop was
 * REGISTERED at all. The emulator exercise that says those things is recorded
 * in the body of the commit that fills the migration.
 *
 * ## Why two columns and not one
 *
 * They are one hop because they answer one question the export could not ask:
 * what actually happened, as against what the app set out to do. `workBegan`
 * separates a set that held nothing from a set that never started; and a set
 * that never started is marked `failed` BY DERIVATION, so a reader meeting it
 * needs `failedByLifter` in the same document to know nobody said so.
 * Splitting them would ship a build whose export answers half the question,
 * and would cost the lifter a second migration for no gain.
 *
 * ## The shape, and why it is this one
 *
 * NULLABLE WITH NO DEFAULT, which is [Migration13To14Test]'s shape and
 * deliberately not a defaulted NOT NULL append. Each column has a real absent
 * state that no value stands for: every row written before v15 was recorded by
 * a build that could observe neither fact. A default of 1 on `workBegan` would
 * assert of the whole archive that the app watched every set start, and a
 * default of 0 on `failedByLifter` would assert that every historical failure
 * was the app's derivation and never the lifter's word.
 *
 * ## The backfills that are refused
 *
 * `workBegan` could plausibly be set from whether a prep-window stream exists.
 * It is refused: `PrepWindowPolicy.of` also returns null when the two instants
 * invert, which a mid-set clock correction reaches, so that backfill would
 * mark sets abandoned because `System.currentTimeMillis` moved. `failedByLifter`
 * has no candidate at all -- the tap lived in `SetRatingTracker`'s memory for
 * the life of the rest screen and was discarded -- and inventing one would
 * name an author for every failure in the lifter's history.
 */
class Migration14To15Test {
    private val json = Json { ignoreUnknownKeys = true }

    /** [Migration10To11Test]'s lookup, stated again because it is private there. */
    private fun schema(version: Int): File {
        val relative = "schemas/com.macrophage.barspeed.data.AppDatabase/$version.json"
        val candidates = listOf(File(relative), File("core/data/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error("no committed schema baseline for v$version; tried ${candidates.map { it.absolutePath }}")
    }

    private fun columnsOf(version: Int, table: String): Map<String, Triple<String, Boolean, String?>> {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        val entity =
            root.getValue("database").jsonObject.getValue("entities").jsonArray
                .map { it.jsonObject }
                .first { it.getValue("tableName").jsonPrimitive.content == table }
        return entity.getValue("fields").jsonArray.associate { field ->
            val f = field.jsonObject
            f.getValue("columnName").jsonPrimitive.content to
                Triple(
                    f.getValue("affinity").jsonPrimitive.content,
                    f["notNull"]?.jsonPrimitive?.content?.toBoolean() ?: false,
                    f["defaultValue"]?.jsonPrimitive?.content,
                )
        }
    }

    private fun declaredVersion(version: Int): Int {
        val root = json.parseToJsonElement(schema(version).readText()).jsonObject
        return root.getValue("database").jsonObject.getValue("version").jsonPrimitive.int
    }

    /** Every statement the migration asks for, in the order it asks for them. */
    private fun executedSql(): List<String> {
        val executed = mutableListOf<String>()
        val recorder =
            Proxy.newProxyInstance(
                SupportSQLiteDatabase::class.java.classLoader,
                arrayOf(SupportSQLiteDatabase::class.java),
            ) { _, method, args ->
                if (method.name == "execSQL" && args != null) executed += args[0] as String
                null
            } as SupportSQLiteDatabase
        AppDatabase.MIGRATION_14_15.migrate(recorder)
        return executed
    }

    /**
     * The compiled version, the committed baseline and the migration's own
     * endpoints are one number.
     *
     * The assertion the NEWEST hop owes the constant, moved here from
     * [Migration13To14Test] the way that file took it from its predecessor: a
     * constant left behind at 14 ships a build whose schema the chain cannot
     * reach, and Room throws on the lifter's phone.
     */
    @Test
    fun `the compiled version, the committed baseline and the migration agree on fifteen`() {
        assertEquals(15, DATABASE_VERSION, "DATABASE_VERSION is not the version this migration ends at")
        assertEquals(15, declaredVersion(15), "15.json does not describe version 15")
        assertEquals(14, declaredVersion(14), "14.json does not describe version 14")
        assertEquals(14, AppDatabase.MIGRATION_14_15.startVersion)
        assertEquals(15, AppDatabase.MIGRATION_14_15.endVersion)
    }

    /**
     * v15 differs from v14 by exactly two nullable columns on set_records.
     *
     * The whole risk of a hand-written migration is that the entity moved
     * further than the SQL did. This reads the difference off Room's own
     * generated descriptions, so a third column, a retyped column and a
     * dropped one are all caught -- none of which the statements below would
     * carry.
     */
    @Test
    fun `the schema baselines differ by exactly the two capture columns`() {
        for (table in listOf("raw_streams", "sessions", "plans", "custom_exercises")) {
            assertEquals(
                emptySet(),
                (columnsOf(15, table) - columnsOf(14, table).keys).keys,
                "$table gained a column this migration does not append",
            )
        }
        val gained = columnsOf(15, "set_records") - columnsOf(14, "set_records").keys
        assertEquals(
            setOf("workBegan", "failedByLifter"),
            gained.keys,
            "set_records gained something other than the two capture facts",
        )
        for (name in listOf("workBegan", "failedByLifter")) {
            val (affinity, notNull, default) = gained.getValue(name)
            assertEquals("INTEGER", affinity, "$name is not INTEGER, so it cannot hold a stored boolean")
            assertTrue(!notNull, "$name is NOT NULL, so a row the app could not observe cannot be stored")
            assertNull(default, "$name carries a default, which is an observation nobody made")
        }
    }

    /**
     * Nothing that existed at v14 changed -- and `failed` above all.
     *
     * The near neighbour of adding a column is retyping the one it pairs with.
     * `failed` keeps its type, its nullability and its default here; what
     * changes is that a second column now says whose verdict it is. A
     * migration made of ADD COLUMN statements says nothing about the rest of
     * the table, so a silently retyped column would reach Room's own TableInfo
     * check on a real phone and throw there instead of here.
     */
    @Test
    fun `no column that existed at v14 changed its type, nullability or default`() {
        for (table in listOf("raw_streams", "set_records", "sessions", "plans", "custom_exercises")) {
            val before = columnsOf(14, table)
            val after = columnsOf(15, table)
            assertEquals(
                emptyList(),
                before.keys.filter { it !in after },
                "$table lost a column between v14 and v15",
            )
            assertEquals(
                emptyMap(),
                before.filter { (name, spec) -> after.getValue(name) != spec },
                "$table changed a column that already existed at v14",
            )
        }
        val v15 = columnsOf(15, "set_records")
        assertEquals(Triple("INTEGER", false, null), v15.getValue("actualDurationS"), "actualDurationS changed shape")
        assertEquals(Triple("INTEGER", false, null), v15.getValue("prepS"), "prepS changed shape")
    }

    /**
     * The migration executes exactly the two appends the baselines call for.
     *
     * Read off the real migration body through a recording database, so this
     * is the SQL that will run rather than a second copy of it kept beside the
     * first.
     */
    @Test
    fun `the migration runs two add-column statements and nothing else`() {
        assertEquals(
            listOf(
                "ALTER TABLE set_records ADD COLUMN workBegan INTEGER",
                "ALTER TABLE set_records ADD COLUMN failedByLifter INTEGER",
            ),
            executedSql(),
        )
    }

    /**
     * Both statements are plain appends that cannot rewrite the table.
     *
     * SQLite performs a plain `ADD COLUMN` by appending to the table
     * definition, while every form Room would generate for a table recreate
     * copies rows -- which on this schema means copying every gzipped IMU blob
     * in the lifter's history.
     */
    @Test
    fun `the statements are plain appends and are not destructive`() {
        assertTrue(executedSql().isNotEmpty(), "the migration executes nothing at all")
        for (sql in executedSql()) {
            assertTrue(sql.startsWith("ALTER TABLE "), "not a column append: $sql")
            assertTrue("ADD COLUMN" in sql, "not a column append: $sql")
            assertTrue(
                "NOT NULL" !in sql || "DEFAULT" in sql.uppercase(),
                "a NOT NULL append with no default is refused on a populated table: $sql",
            )
            assertTrue("DROP" !in sql.uppercase() && "RENAME" !in sql.uppercase(), "destructive statement: $sql")
        }
    }

    /**
     * No existing row is given an observation.
     *
     * The pin against both backfills this file's KDoc refuses. A `workBegan`
     * copied from whether a prep window exists would mark a clock-corrected
     * set abandoned; a `failedByLifter` written at all would name an author
     * for every failure the app derived before v15. Either would be
     * indistinguishable, in the export, from a fact the app had recorded.
     */
    @Test
    fun `the migration writes no value into any existing row`() {
        assertEquals(
            emptyList(),
            executedSql().filter { it.uppercase().startsWith("UPDATE ") || it.uppercase().startsWith("INSERT ") },
            "the migration backfills an observation nobody made",
        )
    }
}
