package com.macrophage.barspeed.model

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The parts of [NextSetNudgePolicy] that are complete in this commit: the two
 * authored step rows and their authoring rule, the rung lookup, the plan-value
 * lookup, the queue walk and the two bump arithmetics.
 *
 * What [NextSetNudgePolicy.options] returns is pinned separately, in
 * `NextSetNudgeOptionsTest`, which is pushed red at its own SHA before the
 * implementation lands. Nothing here asserts that it draws anything.
 */
class NextSetNudgePolicyTest {
    @Test
    fun `the pound row is the six steps the owner authored`() {
        assertEquals(listOf(5.0, 10.0, 15.0, 20.0, 25.0, 30.0), NextSetNudgePolicy.LB_STEPS)
    }

    @Test
    fun `the kilogram row is the six steps the owner authored`() {
        assertEquals(listOf(2.5, 5.0, 7.5, 10.0, 12.5, 15.0), NextSetNudgePolicy.KG_STEPS)
    }

    @Test
    fun `every pound step is a whole multiple of the gym increment`() {
        NextSetNudgePolicy.LB_STEPS.forEach { step ->
            assertEquals(
                0.0,
                step % EffortScale.GYM_INCREMENT_MULTIPLE,
                1e-9,
                "$step lb is not a whole multiple of ${EffortScale.GYM_INCREMENT_MULTIPLE}",
            )
        }
    }

    @Test
    fun `every kilogram step is a whole multiple of this table's own finer rule`() {
        NextSetNudgePolicy.KG_STEPS.forEach { step ->
            assertEquals(
                0.0,
                step % NextSetNudgePolicy.KG_STEP_MULTIPLE,
                1e-9,
                "$step kg is not a whole multiple of ${NextSetNudgePolicy.KG_STEP_MULTIPLE}",
            )
        }
    }

    /**
     * The one property that makes "authored, never converted" checkable rather
     * than merely stated. A converted 5 lb is 2.267 kg and a converted 2.5 kg
     * is 5.51 lb; nothing in either row is within a gram or an ounce of a
     * figure from the other, so a row regenerated by [WeightUnit] reds here.
     */
    @Test
    fun `no step in either row is a conversion of a step in the other`() {
        NextSetNudgePolicy.LB_STEPS.forEach { lb ->
            val asKg = WeightUnit.LB.toKg(lb)
            NextSetNudgePolicy.KG_STEPS.forEach { kg ->
                assertTrue(
                    Math.abs(asKg - kg) > 0.01,
                    "$lb lb converts to $asKg kg, which collides with the authored $kg kg step",
                )
            }
        }
    }

    @Test
    fun `the rep row offers one and two, and nothing further from the claim`() {
        assertEquals(listOf(1, 2), NextSetNudgePolicy.REP_STEPS)
    }

    @Test
    fun `the timed row offers five, ten and fifteen seconds`() {
        assertEquals(listOf(5, 10, 15), NextSetNudgePolicy.TIME_STEPS_S)
    }

    @Test
    fun `each headroom anchor maps back to its own rung`() {
        HeadroomTier.entries.forEach { tier ->
            assertEquals(tier, HeadroomTier.ofRpe(tier.rpe), "rpe ${tier.rpe} did not map back to $tier")
        }
    }

    @Test
    fun `a counted-end rating is not a headroom rung`() {
        (EffortScale.PROXIMITY_FLOOR_RPE..10).forEach { rpe ->
            assertNull(HeadroomTier.ofRpe(rpe), "rpe $rpe is on the counted end and is not a headroom rung")
        }
    }

    @Test
    fun `an unanchored rating is not a headroom rung`() {
        EffortScale.UNANCHORED_RPE.forEach { rpe ->
            assertNull(HeadroomTier.ofRpe(rpe), "rpe $rpe has no tile, so it names no rung")
        }
    }

    @Test
    fun `an unrated set is not a headroom rung`() {
        assertNull(HeadroomTier.ofRpe(null))
    }

    @Test
    fun `an absent progression declaration means weight`() {
        assertEquals(ProgressionKind.WEIGHT, ProgressionKind.ofPlan(null))
    }

    @Test
    fun `each declared progression value names its own kind`() {
        assertEquals(ProgressionKind.WEIGHT, ProgressionKind.ofPlan("weight"))
        assertEquals(ProgressionKind.REPS, ProgressionKind.ofPlan("reps"))
        assertEquals(ProgressionKind.TIME, ProgressionKind.ofPlan("time"))
        assertEquals(ProgressionKind.NONE, ProgressionKind.ofPlan("none"))
    }

    @Test
    fun `a value the gate would have refused reads as the default rather than throwing`() {
        assertEquals(ProgressionKind.WEIGHT, ProgressionKind.ofPlan("volume"))
    }

    @Test
    fun `sets left counts the run of the same exercise ahead of the finished set`() {
        assertEquals(
            2,
            NextSetNudgePolicy.setsLeftInExercise("back_squat", listOf("back_squat", "back_squat", "bench_press")),
        )
    }

    @Test
    fun `sets left stops at the first slot of another movement`() {
        assertEquals(
            0,
            NextSetNudgePolicy.setsLeftInExercise("back_squat", listOf("bench_press", "back_squat")),
        )
    }

    @Test
    fun `sets left is zero at the end of the queue`() {
        assertEquals(0, NextSetNudgePolicy.setsLeftInExercise("back_squat", emptyList()))
    }

    @Test
    fun `an ad-hoc set belongs to no block and has no sets left`() {
        assertEquals(0, NextSetNudgePolicy.setsLeftInExercise(null, listOf("back_squat", "back_squat")))
    }

    /**
     * The appended-set case the arithmetic form gets wrong. The finished slot
     * is set 3 of 3, so `setsInExercise - setIndexInExercise - 1` is 0, and the
     * appended fourth is sitting in the queue right behind it.
     */
    @Test
    fun `a set appended at the rack counts as a set left`() {
        assertEquals(1, NextSetNudgePolicy.setsLeftInExercise("back_squat", listOf("back_squat")))
    }

    @Test
    fun `a pound bump lands on the exact pound figure, not a rounded conversion`() {
        val fortyFiveLb = WeightUnit.LB.toKg(45.0)
        val bumped = NextSetNudgePolicy.bumpedLoadKg(
            fortyFiveLb,
            NextSetNudge(ProgressionKind.WEIGHT, 10.0, "+10 lb"),
            WeightUnit.LB,
        )
        assertEquals(55.0, WeightUnit.LB.fromKg(bumped!!), 1e-9)
    }

    @Test
    fun `a kilogram bump adds the authored kilogram figure`() {
        val bumped = NextSetNudgePolicy.bumpedLoadKg(
            20.0,
            NextSetNudge(ProgressionKind.WEIGHT, 2.5, "+2.5 kg"),
            WeightUnit.KG,
        )
        assertEquals(22.5, bumped!!, 1e-9)
    }

    @Test
    fun `a bump onto a stripped bar is a statement about zero, not an absence`() {
        val bumped = NextSetNudgePolicy.bumpedLoadKg(
            0.0,
            NextSetNudge(ProgressionKind.WEIGHT, 5.0, "+5 kg"),
            WeightUnit.KG,
        )
        assertEquals(5.0, bumped!!, 1e-9)
    }

    @Test
    fun `a load nobody stated stays unstated rather than becoming the step`() {
        assertNull(
            NextSetNudgePolicy.bumpedLoadKg(
                null,
                NextSetNudge(ProgressionKind.WEIGHT, 10.0, "+10 lb"),
                WeightUnit.LB,
            ),
        )
    }

    @Test
    fun `a rep bump adds whole reps`() {
        assertEquals(10, NextSetNudgePolicy.bumpedCount(8, NextSetNudge(ProgressionKind.REPS, 2.0, "+2 reps")))
    }

    @Test
    fun `a hold bump adds whole seconds`() {
        assertEquals(45, NextSetNudgePolicy.bumpedCount(30, NextSetNudge(ProgressionKind.TIME, 15.0, "+15 s")))
    }

    @Test
    fun `a count nobody prescribed stays unprescribed`() {
        assertNull(NextSetNudgePolicy.bumpedCount(null, NextSetNudge(ProgressionKind.REPS, 1.0, "+1 rep")))
    }
}
